[phases.setup]
nixPkgs = ["python312", "postgresql_16"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && cd backend && pip install -r requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"