name: Check Markdown links
on:
  pull_request:
    paths:
      - '**.md'
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          folder-path: '.'
          file-extension: '.md'
          config-file: 'docs/markdown-link-check-config.json'

      - name: Upload results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: broken-links-report
          path: link-check-results.md
